name: Create Renovate Data

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * *"

permissions:
  contents: read

jobs:
   
  update:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Use node 20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
          
      - name: Download recent extensions
        run: |
          .\01-update-extension-cache.ps1
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        shell: pwsh 
        
      - name: Generate azure-pipelines-marketplace-tasks.json
        run: |
          .\02-generate-renovate-data-marketplace.ps1
        shell: pwsh 

      - name: Generate azure-pipelines-builtin-tasks.json
        run: |
          .\03-generate-renovate-data-builtin.ps1
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_ORG: ${{ vars.AZURE_DEVOPS_ORG }}
        shell: pwsh
