name: Create Renovate Data

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * *"

permissions:
  contents: read

jobs:
   
  update:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: Use node 
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json
          
      - name: Download recent extensions
        run: |
          .\01-update-extension-cache.ps1
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        shell: pwsh 
        
      - name: Generate azure-pipelines-marketplace-tasks.json
        run: |
          .\02-generate-renovate-data-marketplace.ps1
        shell: pwsh 

      - name: Generate azure-pipelines-builtin-tasks.json
        run: |
          .\03-generate-renovate-data-builtin.ps1
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_ORG: ${{ vars.AZURE_DEVOPS_ORG }}
        shell: pwsh
